feed/urls.py
from unicodedata import name
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

# FROM feed FILE, IMPORT urls.py AS feed_urls
from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField


# THE THINGS YOU NEED IN Post CLASS
# TEXT
# IMAGE
class Post(models.Model):
    # IT TAKES A CHARACTER LENGTH OF 140 AND IT SHOULDN'T BE NULL NOR BLANK
    text = models.CharField(max_length=140, blank=False, null=False)
    # UPLOAD ANY FORM OF IMAGE
    image = ImageField()


    # THIS WILL UPDATE POST TITLE
    def __str__(self):
        return self.text

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image = forms.FileField()
    # IT WILL SHOW AS "Description"
    text = forms.CharField(label="Description")

feed/views.py
# Go check ccbv.co.uk

from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm
# FROM models.py IMPORT CLASS NAME 'Post'
from .models import Post

class HomePageView(TemplateView):
    # THIS IS THE ATTRIBUTE OF TemplateView
    template_name = "home.html"

# CHECK  OUT  ccbv.co.uk
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
    # THESE 'my_thing' & 'posts' ARE USED IN "home.html"
        context['my_thing'] = "Hello world :), this is dynamic"
    # FROM models.py, USING CLASS NAMED 'Post'
    # OR FROM feed/migrations/0001_initial.py -> IN operations IN fields={id & text}
    # GET ALL THE Post objects AND ORDER THEM BY ID DESCENDING ORDER (NEWEST AT THE VERY TOP)
    # THESE 'posts' & 'posts' ARE USED IN "home.html"
        context['posts'] = Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    template_name = "detail.html"
    model = Post


class AddPostView(FormView):
    template_name = "new_post.html"
    # FROM forms.py
    form_class = PostForm
    success_url = "/"

#  CHECK OUT IN ccbv.co.uk -> FormView
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        print("form.cleaned_data['text']")
        print("form.cleaned_data['image']")
        #  CREATE NEW POST
        new_object = Post.objects.create(
            text = form.cleaned_data['text'],
            image = form.cleaned_data['image']
        )
        # self.request IS COMING FROM def dispatch() WITHIN THIS CLASS
        messages.add_message(self.request, messages.SUCCESS, 'Your Post was successful')
        #  IF IT IS VALID, THEN RETURN TO HOME PAGE
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} DEFAULT TITLE {% endblock%}</title>
<!-- BOOTSTRAP CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<!-- NAVIGATION FROM 'includes/navbar.html'-->
    {% include "includes/navbar.html" %}
    
<!-- IF THE POST WAS SUCCESSFUL -->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <div class="bg-{% if message.tags %}{{ message.tags }}{%else%} success {%endif%} bg-gradient text-center text-white py-4">
                {{ message }}
            </div>
        {% endfor %}
    </ul>
    {% endif %}



    
<!-- WHERE ALL THE TEXT AND FILES ARE UPLOADED -->
    <!-- THIS 'container' CLASS IS FROM BOOTSTRAP -->
    <div class="container">
        {% block body %} {% endblock %}
    </div>

</body>
</html>

templates/detail.html
{% extends "base.html" %}


{%block title%} {{object.text}} {% endblock%}

{%block body%}
<!-- DON'T NEED THIS ANYMORE, SINCE WE HAVE NAVIGATION BAR -->
    <!-- <a href="{% url 'feed:index' %}">&larr; Go back</a> -->
    <div class="row">
        <div class="col-sm-10 py-5">
            {{object.text}}
            <img src="{{object.image.url}}" class"rounded">
        </div>
    </div>
{%endblock%}

templates/home.html
<!-- GETTING STUFF FROM base.html -->
{% extends "base.html" %}

{% load thumbnail %}

<!-- TITLE -->
<!-- DEFAULT HAS BEEN OVERWRITTEN WITH BELOW -->
{% block title %} My super awesome homepage{% endblock %}

<!-- BODY -->
{% block body %}
<!-- FROM views.py -->
    <!-- <h1>{{ my_thing }}</h1> <br> -->
<!-- DON'T NEED THIS ANYMORE SINCE, WE HAVE A NAVIGATION BAR -->
    <!-- <a href={% url 'feed:post' %}> Add a new post</a> <br> -->

<!-- IMPORTED A CLASS FROM models.py, AND THEN
    USED IN views.py-->
    <div class="row">
        {% for post in posts %} 
           <!-- DIFFERENT VIEW FOR DIFFERENT DEVICES  -->
        <div class="col col-sm-6 col md-3">
            <!-- MARGIN TOP & BOTTOM 4 -->
            <div class="card my-4">
                <!-- LOAD AN IMAGE USING thumbnail PACKAGE FROM GITHUB-->
                {% thumbnail post.image "200x200" crop="center" as im %}
                <img src="{{ im.url }}" class="card-img-top" alt="...">
                {% endthumbnail %}
                <div class="card-body">
                    <p class="card-text">{{ post.text }}</p>
                    <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Full Image</a>
                </div>
            </div>
        </div>    
        {% empty %}
            <div class="col-sm-6 offset-3 text-center py-5 my-5">
                <h3>Welcome!</h3>
                <p>Add your first image!</p>
                <a href="{% url 'feed:post' %}" class="btn btn-lg btn-success">Upload Your First Image</a>
            </div>

        {% endfor %}
    </div>
        {% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Image Sharer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <!-- feed:index FROM urls.py -->
                    <a class="nav-link active" aria-current="page" href={% url 'feed:index' %}>Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'feed:post' %}>Add New Image</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/new_post.html
{% extends "base.html" %}


{%block title%} Upload a new image {% endblock%}

{%block body%}
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
        <h2>Upload an Image!</h2>
        {% csrf_token %}
        {{form.as_p}}
        <div>
            <button type="submit" class="btn btn-lg btn-success">Submit Form</button>
        </div>
    </form>
{%endblock%}